import AppPublicLayout from "@/components/layouts/AppPublicLayout";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();

  return (
    <html lang={locale} className={inter.className}>
      <body className="">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <AppPublicLayout>{children}</AppPublicLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
